package:
  name: zeromq
  version: 3.2.3

source:
  fn: zeromq-3.2.3.tar.gz
  url: http://download.zeromq.org/zeromq-3.2.3.tar.gz
  sha1: 6857a3a0e908eca58f7c0f90e2ba4695f6700957

build:
  number: 1

about:
  home: http://zeromq.org
  license: LGPL
