package:
  name: nodejs
  version: 0.10.22

source:
  fn: node-v0.10.22.tar.gz
  url: http://nodejs.org/dist/v0.10.22/node-v0.10.22.tar.gz
  sha1: d7c6a39dfa714eae1f8da7a00c9a07efd74a03b3

build:
  number: 0

about:
  home: http://nodejs.org
  license: MIT
