package:
  name: pyzmq
  version: 13.1.0

source:
  fn: pyzmq-13.1.0.tar.gz
  url: https://pypi.python.org/packages/source/p/pyzmq/pyzmq-13.1.0.tar.gz
  md5: b54a2209a4efed93ed00282d949db8d9
#  patches:
   # List any patch files here
   # - fix.patch

build:
  number: 1

requirements:
  build:
    - python
    - zeromq [not win]

  run:
    - python
    - zeromq [not win]

test:
  # Python imports
  imports:
    - zmq

  commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.
    - nosetests zmq.tests


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  requires:
    # Put any additional test requirements here.  For example
    - nose

about:
  home: http://github.com/zeromq/pyzmq
  summary: http://zeromq.github.io/pyzmq/changelog.html
  
  license: BSD License and GNU Library or Lesser General Public License (LGPL)

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
